kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    name: com-ext
    targetPort: 4505
    port: 4505
  - protocol: "TCP"
    name: com-int
    targetPort: 4506
    port: 4506
  externalIPs:
    - {{ minikube_ip }}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      volumes:
      - name: test-volume
        hostPath:
          path: /vm-salt-lab
      containers:
      - name: saltstack
        image: mxrss/salt-stack:gitfs
        volumeMounts:
          - mountPath: /etc/salt/test
            name: test-volume
        command: ["salt-master", "-l", "debug", "-c", "/etc/salt/test" ]

       