# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.


$script = <<SCRIPT
  & "c:\\salt\\salt-call.bat" state.highstate --local
  & "c:\\salt\\salt-call.bat" state.highstate --local
  gci Env:
SCRIPT

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.define "web-1" do |web|
    web.vm.box = "mxrss2/win2k12-r2-salt"
    web.vm.box_version = "0.1.0"

    web.vm.communicator = "winrm"
    web.winrm.username = "Administrator"
    web.winrm.password = "vagrant"
    web.vm.boot_timeout = 600
    web.vm.graceful_halt_timeout = 600
    web.vm.provision "shell",
     inline: $script, env: {"SALT_MASTER" => ENV['SALT_MASTER_TO_CONFIGURE'],  "HOST_NAME" => "Web1", "SERVER_ROLE" => "web" }
    web.vm.synced_folder "./provisioner", "C:\\Salt\\srv\\salt"
    web.vm.network :forwarded_port, guest: 5985, host: 59851, id: "winrm", auto_correct: true
    web.vm.network "private_network", type: "dhcp"
   

  end

  config.vm.define "web-2" do |web|
    web.vm.box = "mxrss2/win2k12-r2-salt"
    web.vm.box_version = "0.1.0"

    web.vm.communicator = "winrm"
    web.winrm.username = "Administrator"
    web.winrm.password = "vagrant"
    web.vm.boot_timeout = 600
    web.vm.graceful_halt_timeout = 600
    web.vm.provision "shell",
     inline: $script, env: {"SALT_MASTER" => ENV['SALT_MASTER_TO_CONFIGURE'],  "HOST_NAME" => "Web2", "SERVER_ROLE" => "web"}
    web.vm.synced_folder "./provisioner", "C:\\Salt\\srv\\salt"
    web.vm.network "private_network", type: "dhcp"
    
    web.vm.network :forwarded_port, guest: 5985, host: 59850, id: "winrm", auto_correct: true
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.box = "mxrss2/linux-xental-haproxy-salt"
    proxy.vm.box_version = "0.1.0"
    proxy.vm.network "private_network", type: "dhcp"
    proxy.vm.network :forwarded_port, guest: 80, host: 3000, id: "http_loadbalance"
    proxy.vm.network :forwarded_port, guest: 3001, host: 3001, id: "stats"
    proxy.vm.network :forwarded_port, guest: 22, host: 2222, id: "sshd", auto_correct: true

    # proxy.vm.provision "shell",
    #env: {"SALT_MASTER" => ENV['SALT_MASTER_TO_CONFIGURE'],  "HOST_NAME" => "proxy", "SERVER_ROLE" => "proxy"} 

  end

  config.vm.box_download_insecure = true

   
end
