kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    name: com-ext
    #nodePort: 32000
    targetPort: 4505
    port: 4505
  - protocol: "TCP"
    name: com-int
    #nodePort: 32001
    targetPort: 4506
    port: 4506
  externalIPs:
    - 192.168.99.100
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      volumes:
      - name: test-volume
        hostPath:
          path: /test2/config
      containers:
      - name: saltstack
        image: mxrss/salt-stack
        volumeMounts:
          - mountPath: /etc/salt/test
            name: test-volume
        command: ["salt-master", "-l", "debug", "-c", "/etc/salt/test" ]
      environment:
        name: MINIKUBE
        value: "$env:Minikubeip"
        #args: ["/etc/salt/test"]
  

       